<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.8.1 setup script
 * Date: Fri, 26 Apr 2013 15:37:16 +0000
 */

$cfg['DefaultLang'] = 'ru';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>